<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\SportHub.Gamification.Domain\SportHub.Gamification.Domain.csproj" />
    <ProjectReference Include="..\..\..\Shared\SportHub.Shared.Abstractions\SportHub.Shared.Abstractions.csproj" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

</Project>
