<#
.SYNOPSIS
    Create or destroy a preview environment for a user story branch.
.DESCRIPTION
    Deploys isolated Container Apps per hu/* branch so developers
    and QA can test each User Story in a dedicated environment.
    
    Each preview gets its own pair of Container Apps (API + Web)
    that share the same ACA Environment, PostgreSQL, Redis, and
    Service Bus as the staging environment.
    
    Previews auto-scale to 0 when idle to minimize cost.
.PARAMETER Action
    'create' to deploy, 'destroy' to tear down.
.PARAMETER BranchName
    Sanitized branch name used as suffix for container names.
    Generated by the preview.yml workflow: lowercase, alphanumeric + hyphens.
.PARAMETER ImageTag
    Docker image tag to deploy (e.g., "preview-hu-f001-us-001-a1b2c3d").
    Only required for 'create' action.
.PARAMETER ResourceGroup
    Azure Resource Group name. Default: rg-sporthub-staging-v2
.Parameter EnvironmentName
    ACA Environment name. Default: cae-sport-staging-w4wuoo
.PARAMETER Location
    Azure region. Default: eastus
.EXAMPLE
    # Create preview
    .\deploy-preview.ps1 -Action create -BranchName "hu-f001-us-001" -ImageTag "preview-hu-f001-us-001-a1b2c3d"

    # Destroy preview
    .\deploy-preview.ps1 -Action destroy -BranchName "hu-f001-us-001"
#>

[CmdletBinding()]
param(
    [Parameter(Mandatory)]
    [ValidateSet('create', 'destroy')]
    [string]$Action,

    [Parameter(Mandatory)]
    [string]$BranchName,

    [Parameter()]
    [string]$ImageTag = 'staging',

    [Parameter()]
    [string]$ResourceGroup = 'rg-sporthub-staging-v2',

    [Parameter()]
    [string]$EnvironmentName = 'cae-sport-staging-w4wuoo',

    [Parameter()]
    [string]$Location = 'eastus',

    [Parameter()]
    [string]$PreviewCpu = '0.5',

    [Parameter()]
    [string]$PreviewMemory = '1Gi',

    [Parameter()]
    [string]$RegistryServer = 'ghcr.io',

    [Parameter()]
    [string]$RegistryUsername = 'Tribbu-Platform',

    [Parameter()]
    [string]$PostgresPassword = 'PLACEHOLDER'
)

$ErrorActionPreference = 'Stop'

# ============================================================
# Naming
# ============================================================
$apiName = "pr-${BranchName}-api"
$webName = "pr-${BranchName}-web"
$tags = @{
    environment = 'preview'
    branch = $BranchName
    project = 'sport-hub-connect'
    managedBy = 'preview-pipeline'
    cleanup = 'auto'
}

# ============================================================
# Action: Create
# ============================================================
if ($Action -eq 'create') {
    Write-Host "" -ForegroundColor Cyan
    Write-Host "   Creating Preview Environment" -ForegroundColor Cyan
    Write-Host "  Branch: $BranchName" -ForegroundColor Yellow
    Write-Host "  Image:  $ImageTag" -ForegroundColor Yellow
    Write-Host "" -ForegroundColor Cyan

    #  Check if already exists 
    $apiExists = az containerapp show --name $apiName --resource-group $ResourceGroup --query 'name' -o tsv 2>$null
    
    if ($apiExists) {
        Write-Host "    Preview already exists. Updating images..." -ForegroundColor Yellow
        
        # Update API container image
        # Note: 'az containerapp update' triggers a new revision automatically,
        # no manual restart needed.
        az containerapp update `
            --name $apiName `
            --resource-group $ResourceGroup `
            --image "ghcr.io/tribbu-platform/sporthub-connect/api:${ImageTag}" `
            --output none
        Write-Host "   API updated to $ImageTag"
        
        # Update Web container image
        az containerapp update `
            --name $webName `
            --resource-group $ResourceGroup `
            --image "ghcr.io/tribbu-platform/sporthub-connect/web:${ImageTag}" `
            --output none
        Write-Host "   Web updated to $ImageTag"
        
        Write-Host "   Preview updated and restarted!"
        return
    }

    #  Get Environment ID 
    $envId = az containerapp env show `
        --name $EnvironmentName `
        --resource-group $ResourceGroup `
        --query 'id' -o tsv
    
    if (-not $envId) {
        Write-Error "ACA Environment '$EnvironmentName' not found in resource group '$ResourceGroup'. Run deploy-staging.ps1 first."
        exit 1
    }

    #  Create API Container App 
    Write-Host "`n   Creating API container..." -ForegroundColor Green
    az containerapp create `
        --name $apiName `
        --resource-group $ResourceGroup `
        --environment $EnvironmentName `
        --image "ghcr.io/tribbu-platform/sporthub-connect/api:${ImageTag}" `
        --ingress external `
        --target-port 8080 `
        --transport http `
        --cpu $PreviewCpu `
        --memory $PreviewMemory `
        --min-replicas 0 `
        --max-replicas 2 `
        --registry-server $RegistryServer `
        --registry-username $RegistryUsername `
        --registry-password "$env:GHCR_PASSWORD" `
        --tags @($tags.Keys | ForEach-Object { "$_=$($tags[$_])" }) `
        --output table

    #  Configure API env vars 
    Write-Host "   Configuring API environment..." -ForegroundColor Green
    
    # Get connection strings from staging resources
    $pgHost = az postgres flexible-server show --name "psql-sport-staging-w4wuoo" --resource-group $ResourceGroup --query 'fullyQualifiedDomainName' -o tsv 2>$null
    $redisHost = az redis show --name "redis-sport-staging-w4wuoo" --resource-group $ResourceGroup --query 'hostName' -o tsv 2>$null
    $redisKey = az redis list-keys --name "redis-sport-staging-w4wuoo" --resource-group $ResourceGroup --query 'primaryKey' -o tsv 2>$null
    
    # Note: secrets should come from Key Vault or GitHub Secrets ideally.
    # For preview, we use shared staging resources with mock/dev values.
    # In production, use managed identities + Key Vault.
    az containerapp update `
        --name $apiName `
        --resource-group $ResourceGroup `
        --set-env-vars `
            "ASPNETCORE_ENVIRONMENT=Preview" `
            "ASPNETCORE_URLS=http://+:8080" `
            "ConnectionStrings__PostgreSQL=Host=${pgHost};Port=5432;Database=sporthub;Username=sporthub_admin;Password=${PostgresPassword};SSL Mode=Require;Trust Server Certificate=true" `
            "ConnectionStrings__Redis=${redisHost}:6380,password=${redisKey},ssl=True,abortConnect=False" `
            "ConnectionStrings__RabbitMQ=amqp://sporthub:placeholder@localhost:5672" `
            "Auth0__Domain=$env:AUTH0_DOMAIN" `
            "Auth0__Audience=$env:AUTH0_AUDIENCE" `
            "Auth0__ClientId=$env:AUTH0_CLIENT_ID" `
            "Auth0__ClientSecret=$env:AUTH0_CLIENT_SECRET" `
        --output none 2>$null

    #  Create Web Container App 
    Write-Host "`n   Creating Web container..." -ForegroundColor Green
    
    # Get API FQDN for the WEB's NEXT_PUBLIC_API_URL
    $apiFqdn = az containerapp show --name $apiName --resource-group $ResourceGroup --query 'properties.configuration.ingress.fqdn' -o tsv
    
    az containerapp create `
        --name $webName `
        --resource-group $ResourceGroup `
        --environment $EnvironmentName `
        --image "ghcr.io/tribbu-platform/sporthub-connect/web:${ImageTag}" `
        --ingress external `
        --target-port 3000 `
        --transport http `
        --cpu 0.25 `
        --memory 0.5Gi `
        --min-replicas 0 `
        --max-replicas 2 `
        --registry-server $RegistryServer `
        --registry-username $RegistryUsername `
        --registry-password "$env:GHCR_PASSWORD" `
        --tags @($tags.Keys | ForEach-Object { "$_=$($tags[$_])" }) `
        --env-vars `
            "NODE_ENV=production" `
            "NEXT_PUBLIC_API_URL=https://${apiFqdn}" `
            "NEXT_TELEMETRY_DISABLED=1" `
            "HOSTNAME=0.0.0.0" `
            "PORT=3000" `
        --output table

    #  Configure health probes 
    Write-Host "   Configuring health probes..." -ForegroundColor Green
    
    # API probes
    az containerapp revision copy `
        --name $apiName `
        --resource-group $ResourceGroup `
        --probe-set liveness http get path=/health port=8080 initialDelaySeconds=10 periodSeconds=15 `
        --probe-set readiness http get path=/health/ready port=8080 initialDelaySeconds=5 periodSeconds=10 `
        --probe-set startup http get path=/health port=8080 initialDelaySeconds=0 periodSeconds=5 failureThreshold=30 `
        --output none 2>$null
    
    # Web probes
    az containerapp revision copy `
        --name $webName `
        --resource-group $ResourceGroup `
        --probe-set liveness http get path=/api/health port=3000 initialDelaySeconds=10 periodSeconds=15 `
        --probe-set readiness http get path=/api/health port=3000 initialDelaySeconds=5 periodSeconds=10 `
        --probe-set startup http get path=/api/health port=3000 initialDelaySeconds=0 periodSeconds=5 failureThreshold=30 `
        --output none 2>$null

    #  Output URLs 
    $apiFqdn = az containerapp show --name $apiName --resource-group $ResourceGroup --query 'properties.configuration.ingress.fqdn' -o tsv
    $webFqdn = az containerapp show --name $webName --resource-group $ResourceGroup --query 'properties.configuration.ingress.fqdn' -o tsv

    Write-Host "`n" -ForegroundColor Green
    Write-Host "   Preview Environment Ready!" -ForegroundColor Green
    Write-Host "" -ForegroundColor Green
    Write-Host "   API:   https://$apiFqdn" -ForegroundColor Yellow
    Write-Host "   Web:   https://$webFqdn" -ForegroundColor Yellow
    Write-Host "   Swagger: https://$apiFqdn/swagger" -ForegroundColor Yellow
    Write-Host "`n" -ForegroundColor Green
}

# ============================================================
# Action: Destroy
# ============================================================
if ($Action -eq 'destroy') {
    Write-Host "" -ForegroundColor Cyan
    Write-Host "    Destroying Preview Environment" -ForegroundColor Cyan
    Write-Host "  Branch: $BranchName" -ForegroundColor Yellow
    Write-Host "" -ForegroundColor Cyan

    $deleted = $false

    # Delete API Container App
    $apiExists = az containerapp show --name $apiName --resource-group $ResourceGroup --query 'name' -o tsv 2>$null
    if ($apiExists) {
        Write-Host "    Deleting API: $apiName"
        az containerapp delete --name $apiName --resource-group $ResourceGroup --yes --output none
        Write-Host "   API deleted"
        $deleted = $true
    }
    else {
        Write-Host "    API container not found (already deleted)"
    }

    # Delete Web Container App
    $webExists = az containerapp show --name $webName --resource-group $ResourceGroup --query 'name' -o tsv 2>$null
    if ($webExists) {
        Write-Host "    Deleting Web: $webName"
        az containerapp delete --name $webName --resource-group $ResourceGroup --yes --output none
        Write-Host "   Web deleted"
        $deleted = $true
    }
    else {
        Write-Host "    Web container not found (already deleted)"
    }

    if ($deleted) {
        # Also try to remove the image tags from GHCR (best-effort, GHCR requires explicit deletion via API)
        Write-Host "`n   Note: Docker images remain in GHCR. To clean them up manually:"
        Write-Host "     gh api -X DELETE /orgs/tribbu-platform/packages/container/sporthub-connect%2Fapi/tags/preview-${BranchName}"
        Write-Host "     gh api -X DELETE /orgs/tribbu-platform/packages/container/sporthub-connect%2Fweb/tags/preview-${BranchName}"

        Write-Host "`n" -ForegroundColor Green
        Write-Host "   Preview Environment Destroyed!" -ForegroundColor Green
        Write-Host "" -ForegroundColor Green
    }
    else {
        Write-Host "`n" -ForegroundColor Yellow
        Write-Host "  Nothing to destroy." -ForegroundColor Yellow
        Write-Host "" -ForegroundColor Yellow
    }
}

